<?php
/**
 * Schema for post types
 * 
 * @since 1.0.0
 * 
 * @author Saurabh Shukla <saurabh@baapwp.me>
 */
return array(
	'lesson' => array(
		'labels' => array(
			'name' => _x( 'Lessons', 'Post type general name', 'textdomain' ),
			'singular_name' => _x( 'Lesson', 'Post type singular name', 'textdomain' ),
			'menu_name' => _x( 'Lessons', 'Admin Menu text', 'textdomain' ),
			'name_admin_bar' => _x( 'Lesson', 'Add New on Toolbar', 'textdomain' ),
			'add_new' => __( 'Add New', 'textdomain' ),
			'add_new_item' => __( 'Add New Lesson', 'textdomain' ),
			'new_item' => __( 'New Lesson', 'textdomain' ),
			'edit_item' => __( 'Edit Lesson', 'textdomain' ),
			'view_item' => __( 'View Lesson', 'textdomain' ),
			'all_items' => __( 'All Lessons', 'textdomain' ),
			'search_items' => __( 'Search Lessons', 'textdomain' ),
			'parent_item_colon' => __( 'Parent Lessons:', 'textdomain' ),
			'not_found' => __( 'No lessons found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No lessons found in Trash.', 'textdomain' ),
			'featured_image' => _x( 'Lesson Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'set_featured_image' => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'use_featured_image' => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'archives' => _x( 'Lesson archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain' ),
			'insert_into_item' => _x( 'Insert into lesson', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain' ),
			'uploaded_to_this_item' => _x( 'Uploaded to this lesson', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain' ),
			'filter_items_list' => _x( 'Filter lessons list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain' ),
			'items_list_navigation' => _x( 'Lessons list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain' ),
			'items_list' => _x( 'Lessons list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain' ),
		),
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => true,
		'rewrite' => array( 'slug' => 'lesson' ),
		'has_archive' => false,
		'hierarchical' => false,
		'menu_position' => null,
		'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments' ),
		'taxonomies' => array('module'),
	),
	'test' => array(
		'labels' => array(
			'name' => _x( 'Tests', 'Post type general name', 'textdomain' ),
			'singular_name' => _x( 'Test', 'Post type singular name', 'textdomain' ),
			'menu_name' => _x( 'Tests', 'Admin Menu text', 'textdomain' ),
			'name_admin_bar' => _x( 'Test', 'Add New on Toolbar', 'textdomain' ),
			'add_new' => __( 'Add New', 'textdomain' ),
			'add_new_item' => __( 'Add New Test', 'textdomain' ),
			'new_item' => __( 'New Test', 'textdomain' ),
			'edit_item' => __( 'Edit Test', 'textdomain' ),
			'view_item' => __( 'View Test', 'textdomain' ),
			'all_items' => __( 'All Tests', 'textdomain' ),
			'search_items' => __( 'Search Tests', 'textdomain' ),
			'parent_item_colon' => __( 'Parent Tests:', 'textdomain' ),
			'not_found' => __( 'No tests found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No tests found in Trash.', 'textdomain' ),
			'featured_image' => _x( 'Test Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'set_featured_image' => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'use_featured_image' => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'archives' => _x( 'Test archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain' ),
			'insert_into_item' => _x( 'Insert into test', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain' ),
			'uploaded_to_this_item' => _x( 'Uploaded to this test', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain' ),
			'filter_items_list' => _x( 'Filter tests list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain' ),
			'items_list_navigation' => _x( 'Tests list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain' ),
			'items_list' => _x( 'Tests list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain' ),
		),
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => true,
		'rewrite' => array( 'slug' => 'test' ),
		'has_archive' => false,
		'hierarchical' => false,
		'menu_position' => null,
		'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments' ),
		'taxonomies' => array('module'),
	),
	'course' => array(
		'labels' => array(
			'name' => _x( 'Courses', 'Post type general name', 'textdomain' ),
			'singular_name' => _x( 'Course', 'Post type singular name', 'textdomain' ),
			'menu_name' => _x( 'Courses', 'Admin Menu text', 'textdomain' ),
			'name_admin_bar' => _x( 'Course', 'Add New on Toolbar', 'textdomain' ),
			'add_new' => __( 'Add New', 'textdomain' ),
			'add_new_item' => __( 'Add New Course', 'textdomain' ),
			'new_item' => __( 'New Course', 'textdomain' ),
			'edit_item' => __( 'Edit Course', 'textdomain' ),
			'view_item' => __( 'View Course', 'textdomain' ),
			'all_items' => __( 'All Courses', 'textdomain' ),
			'search_items' => __( 'Search Courses', 'textdomain' ),
			'parent_item_colon' => __( 'Parent Courses:', 'textdomain' ),
			'not_found' => __( 'No courses found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No courses found in Trash.', 'textdomain' ),
			'featured_image' => _x( 'Course Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'set_featured_image' => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'use_featured_image' => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'archives' => _x( 'Course archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain' ),
			'insert_into_item' => _x( 'Insert into course', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain' ),
			'uploaded_to_this_item' => _x( 'Uploaded to this course', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain' ),
			'filter_items_list' => _x( 'Filter courses list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain' ),
			'items_list_navigation' => _x( 'Courses list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain' ),
			'items_list' => _x( 'Courses list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain' ),
		),
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => true,
		'rewrite' => array( 'slug' => 'course' ),
		'has_archive' => 'courses',
		'hierarchical' => false,
		'menu_position' => null,
		'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments' ),
		'taxonomies' => array('module'),
	),
	'module' => array(
		'labels' => array(
			'name' => _x( 'Modules', 'Post type general name', 'textdomain' ),
			'singular_name' => _x( 'Module', 'Post type singular name', 'textdomain' ),
			'menu_name' => _x( 'Modules', 'Admin Menu text', 'textdomain' ),
			'name_admin_bar' => _x( 'Module', 'Add New on Toolbar', 'textdomain' ),
			'add_new' => __( 'Add New', 'textdomain' ),
			'add_new_item' => __( 'Add New Module', 'textdomain' ),
			'new_item' => __( 'New Module', 'textdomain' ),
			'edit_item' => __( 'Edit Module', 'textdomain' ),
			'view_item' => __( 'View Module', 'textdomain' ),
			'all_items' => __( 'All Modules', 'textdomain' ),
			'search_items' => __( 'Search Modules', 'textdomain' ),
			'parent_item_colon' => __( 'Parent Modules:', 'textdomain' ),
			'not_found' => __( 'No modules found.', 'textdomain' ),
			'not_found_in_trash' => __( 'No modules found in Trash.', 'textdomain' ),
			'featured_image' => _x( 'Module Cover Image', 'Overrides the “Featured Image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'set_featured_image' => _x( 'Set cover image', 'Overrides the “Set featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'remove_featured_image' => _x( 'Remove cover image', 'Overrides the “Remove featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'use_featured_image' => _x( 'Use as cover image', 'Overrides the “Use as featured image” phrase for this post type. Added in 4.3', 'textdomain' ),
			'archives' => _x( 'Module archives', 'The post type archive label used in nav menus. Default “Post Archives”. Added in 4.4', 'textdomain' ),
			'insert_into_item' => _x( 'Insert into module', 'Overrides the “Insert into post”/”Insert into page” phrase (used when inserting media into a post). Added in 4.4', 'textdomain' ),
			'uploaded_to_this_item' => _x( 'Uploaded to this module', 'Overrides the “Uploaded to this post”/”Uploaded to this page” phrase (used when viewing media attached to a post). Added in 4.4', 'textdomain' ),
			'filter_items_list' => _x( 'Filter modules list', 'Screen reader text for the filter links heading on the post type listing screen. Default “Filter posts list”/”Filter pages list”. Added in 4.4', 'textdomain' ),
			'items_list_navigation' => _x( 'Modules list navigation', 'Screen reader text for the pagination heading on the post type listing screen. Default “Posts list navigation”/”Pages list navigation”. Added in 4.4', 'textdomain' ),
			'items_list' => _x( 'Modules list', 'Screen reader text for the items list heading on the post type listing screen. Default “Posts list”/”Pages list”. Added in 4.4', 'textdomain' ),
		),
		'public' => true,
		'publicly_queryable' => true,
		'show_ui' => true,
		'show_in_menu' => true,
		'query_var' => true,
		'rewrite' => array( 'slug' => 'module' ),
		'has_archive' => false,
		'hierarchical' => true,
		'menu_position' => null,
		'supports' => array( 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments' ),
		'taxonomies' => array('module'),
	),
);